server:
  port: 8010
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?&useSSL=false&serverTimezone=UTC
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
        server-addr: localhost:8848
    sentinel:
      filter:
        # 打开/关闭掉对Spring MVC端点的保护
        enabled: true
        url-patterns: /**
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8012
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: content-center
feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        requestInterceptors:
          - com.itmuch.contentcenter.feignclient.interceptor.TokenRelayRequestIntecepor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
resttemplate:
  sentinel:
    # 设置成false，表示关闭@SentinelRestTemplate注解
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
rocketmq:
  # 启动的name-server的服务地址
  name-server: 127.0.0.1:9876
  producer:
    # 必须指定Group
    group: test-group